# Pizza time !!!!

CREATE TABLE TOPPINGS (
    T_ID INTEGER PRIMARY KEY,
    Piz_ID INTEGER FOREIGN KEY,
    Name TEXT,
    Price FLOAT,
    Cost FLOAT,
    Inventory INTEGER,
    AmountUsed FLOAT
);

CREATE TABLE PIZZA (
    P_ID INTEGER PRIMARY KEY,
    Bprice_ID INTEGER FOREIGN KEY,
    Order_State TEXT,
    Order_Time Float,
    Crust_Type TEXT,
    Pizza_Price FLOAT,
);

CREATE TABLE BASE_PRICE (
    BP_ID INTEGER FOREIGN KEY,
    Price FLOAT,
    Size TEXT,
    Crust TEXT,
    Cost FLOAT,
);

CREATE TABLE ORDERS (
    O_ID INTEGER PRIMARY KEY,
    Cust_ID INTEGER FOREIGN KEY,
    Order_State TEXT,
    C_Price FLOAT,
    B_Price FLOAT,
);

CREATE TABLE DISCOUNT (
    D_ID INTEGER FOREIGN KEY,
    Percent_Off FLOAT,
    Dollar_Off FLOAT,
    Discount_Type TEXT,
);

CREATE TABLE DISCOUNT_O (
    Ord_ID INTEGER FOREIGN KEY,
    Dis_ID INTEGER FOREIGN KEY,
);

CREATE TABLE DISCOUNT_P (
    Piz_ID INTEGER FOREIGN KEY,
    Dis_ID INTEGER FOREIGN KEY,
);

CREATE TABLE CUSTOMER (
    C_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Phone_Number TEXT,
);

CREATE TABLE DINE_IN (
    Cust_ID INTEGER FOREIGN KEY,
    Table_Number INTEGER,
    Seat_Number INTEGER,
);

CREATE TABLE DELIVERY (
    Cust_ID INTEGER FOREIGN KEY,
    Address TEXT,
);

CREATE TABLE TAKEOUT (
    Cust_ID INTEGER FOREIGN KEY,
);









