DROP TABLE IF EXISTS TOPPINGS;

DROP TABLE IF EXISTS PIZZA;

DROP TABLE IF EXISTS BASE_PRICE;

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS DISCOUNT_O;

DROP TABLE IF EXISTS DISCOUNT_P;

DROP TABLE IF EXISTS CUSTOMER;

DROP TABLE IF EXISTS DINE_IN;

DROP TABLE IF EXISTS DELIVERY;

DROP TABLE IF EXISTS TAKE_OUT;

DROP TABLE Pizza_Toppings;